### ISSUE TITLE
Possible memory issue?

### ISSUE THREAD

**Issue by evanvin** [remig/web_lic#11]
The further I progress into editing my instructions, the more memory the app seems to use. Is there a cache that isn't getting cleared, or is there a possible memory leak?

**Comment by remig** [comment]
There's definitely a few memory leaks in Lic, but I think they're relatively small.

The bigger issue: Lic is a big memory hog.  This is by design; I try to use up memory whenever doing so will speed up the app.  Drawing each 3D brick image (PLI & CSI) is slow, so I cache each drawing in an offscreen canvas.  You can see this caching in action.  When you view a page that has not been drawn yet, there's a brief delay in drawing, maybe a half second.  When you go back to the page, it draws instantly, hundreds of times faster than the first draw.

I think this is a fair trade-off, but it can definitely be a problem on big models or machines with little free memory.  Right now, that offscreen cache is unlimited; it will grow until every 3D drawing is cached.  I need to fix this by putting some limits on the cache so it doesn't consume the machines entire memory and crash.  I think I'll also add a UI setting that lets people disable this feature entirely, in case they have really big models and are hitting memory issues.

The the Undo / Redo stack can also suck up memory.  It's currently unlimited.  Each action you perform adds to that stack, using more memory.  I need to put a hard limit on this stack - say, 100 actions?  I'll probably also add a UI setting to set that limit, in case you have a ton of memory or very little.

In the meantime, if you're hitting memory problems, you can try saving your current book, close the tab, open a new tab then reopen the saved book.  It's annoying, but should give you a clean slate, memory-wise.

**Comment by evanvin** [comment]
So I've just been refreshing the page, and that cuts a bit of memory, but I understand what you're talking about. Thanks for explaining it thoroughly. Are you using WebGL at all for added speed advantages?

**Comment by remig** [comment]
Yeah, I draw all the 3D brick images with [Three.jS](https://threejs.org), which is a nice library that draws with WebGL.  The rest of the UI is just simple HTML drawn with [Vue.js](https://vuejs.org/).

For some reason I don't understand, Chrome doesn't seem to fully clear all used memory on page reload.  If Lic is eating a lot of memory, a page reload wipes the 3D image cache and undo stack, so memory use should drop significantly... but it doesn't.  This is true even if you do a hard reload with cache clear.

However, Lic saves your current instruction book and all your work in your browser's Local Storage, which persists across browser cache clears and tab close / open.  So if memory is an issue, you can close your current tab, then reopen Lic in a new tab and be right where you left off.  Doing this will really free a lot of memory.

**Comment by evanvin** [comment]
Interesting. I'm going to look into the memory a little more, because I don't see why this web app can't be a lot quicker and stay constant. Love this project so far though

**Comment by remig** [comment]
I just pushed a new version of Lic (0.45) to the [public site](http://bugeyedmonkeys.com/lic/).  This version includes a whole lot of performance improvements.

I rewrote the 3D rendering engine to use straight, optimal (if complicated) WebGL instead of going through the huge and slow Three.js. Lic now draws all the 3D bits anywhere from 2x to 10x faster for me.

And I was wrong earlier when I said Lic's memory leaks are relatively small. Turns out the navigation tree widget was leaking memory like a sieve.  I rewrote that widget in straight HTML instead of as a Vue component; this cut down memory use over time dramatically.

I also reorganized and optimized the LDraw part library stored on Lic's web server, so that parts can be found and downloaded much faster, which cuts model import time by some 30%.

With all that, I think Lic's performance and memory use is now very reasonable.  I'm going to mark this issue closed, but if anyone is still hitting performance problems, feel free to reopen this.
