### ISSUE TITLE
Won't open my model; generates empty lego instructions

### ISSUE THREAD

**Issue by danielrh** [remig/web_lic#12]
The file is simply ordinary 2xn pieces assembled into a spaceship, created with the Lego Digital Designer and exported to .ldr

Should this work?

[spaceship.zip](https://github.com/remig/web_lic/files/2580412/spaceship.zip)

**Comment by remig** [comment]
Lic assumes the imported model already includes steps, but LDD does not support steps.  That's why your model wasn't importing.

I fixed this in the latest version of Lic (0.43).  If a model has no steps, Lic will now insert a step between every few parts.  You can pick how many parts are added per step when you import the model.

Reload your browser tab to get the newest version of Lic, and try importing your model again.
