### ISSUE TITLE
PNG files corrupt - High Resolution Export

### ISSUE THREAD

**Issue by zktech** [remig/web_lic#4]
I am attempting to do High Resolution PNG exports where I am doing 300dpi. The files generated are not readable as valid PNG files in any program that otherwise takes PNG.

**Comment by remig** [comment]
This is actually a bug in [changeDPI](https://github.com/shutterstock/changeDPI), the 3rd party library I use to set the PNG's DPI.  The bug is fixed in the project but not on NPM yet.  I need to be careful when deploying new versions of Lic to include only the patched changeDPI.  I fixed the live version of Lic at [bugeyedmonkeys.com](http://bugeyedmonkeys.com/lic/), but I'm going to leave this bug open until changeDPI is fixed on NPM and this doesn't happen again. 

Thanks @zktech for reporting this.

**Comment by remig** [comment]
changeDPI is now fixed on NPM as of version 1.0.4, and Lic is using that new version.  This bug shouldn't come up anymore.
