### ISSUE TITLE
Multiple Part Models - Fail to import beyond the first part

### ISSUE THREAD

**Issue by zktech** [remig/web_lic#5]
I am using MLCad to create some models. We have multi-part models. When importing the file only the first model is imported, and there appears to be no effective way to import the additional models.

**Comment by remig** [comment]
I believe this is working as intended.  Lic assumes there is only one 'main' model per LDraw file, and that it is the first model in the file.  Any other models in the file will only be drawn (as sub-models) if they are referenced by the main model.

I'm not sure how it would work otherwise.  If there are two entirely separate models in one LDraw file, there is no information on where to position those two models relative to each other; they would both get drawn in the center of the page, directly inside one another, which is probably not expected or useful.

This limitation is very easy to work around; simply create one new 'main' model at the top of the LDraw file that references and positions all the other models in the file.

**Comment by zktech** [comment]
I need to figure out how to bring models beyond the first one into the main model. Right now I have been doing each piece as sub models I did not know I could combine them into a master model as the first model in the list. I will look into this ASAP. I am working on another model next weekend. 

Bryant Zimmerman 
 
Sr. Systems Architect
Grand Dial Communications, A ZK Tech Inc. Company
616-299-5607 (mobile) 
616-855-1030 Ext. 2003 (office)

----------------------------------------
